"""add_performance_indexes_to_processed_files

Revision ID: 24fcc21ead7a
Revises: ff3bdfed1040
Create Date: 2025-08-27 12:23:02.468192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24fcc21ead7a'
down_revision: Union[str, Sequence[str], None] = 'ff3bdfed1040'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_processed_files_created_status', 'processed_files', ['created_at', 'processing_status'], unique=False)
    op.create_index('ix_processed_files_hash_status', 'processed_files', ['file_hash', 'processing_status'], unique=False)
    op.create_index('ix_processed_files_user_status', 'processed_files', ['user_id', 'processing_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_processed_files_user_status', table_name='processed_files')
    op.drop_index('ix_processed_files_hash_status', table_name='processed_files')
    op.drop_index('ix_processed_files_created_status', table_name='processed_files')
    # ### end Alembic commands ###
