"""add_processed_files_table

Revision ID: ff3bdfed1040
Revises: 0e3ab92a39ce
Create Date: 2025-08-27 12:19:16.969365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff3bdfed1040'
down_revision: Union[str, Sequence[str], None] = '0e3ab92a39ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_files',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('azure_pdf_url', sa.String(), nullable=False),
    sa.Column('azure_excel_url', sa.String(), nullable=True),
    sa.Column('processing_status', sa.String(), nullable=False),
    sa.Column('processing_time_seconds', sa.Float(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_files_file_hash'), 'processed_files', ['file_hash'], unique=False)
    op.create_index(op.f('ix_processed_files_id'), 'processed_files', ['id'], unique=False)
    op.create_index(op.f('ix_processed_files_user_id'), 'processed_files', ['user_id'], unique=False)
    op.create_index(op.f('ix_stripe_events_id'), 'stripe_events', ['id'], unique=False)
    op.drop_index(op.f('ix_subscription_plans_name'), table_name='subscription_plans')
    op.create_index(op.f('ix_subscription_plans_id'), 'subscription_plans', ['id'], unique=False)
    op.drop_index(op.f('ix_transactions_stripe_processed_at'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_user_processed'), table_name='transactions')
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.drop_index(op.f('ix_user_subscriptions_status'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_user_created'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_user_status'), table_name='user_subscriptions')
    op.create_index(op.f('ix_user_subscriptions_id'), 'user_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_subscription_plan_id'), 'user_subscriptions', ['subscription_plan_id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_user_subscriptions_subscription_plan_id'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_id'), table_name='user_subscriptions')
    op.create_index(op.f('ix_user_subscriptions_user_status'), 'user_subscriptions', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_user_created'), 'user_subscriptions', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_status'), 'user_subscriptions', ['status'], unique=False)
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.create_index(op.f('ix_transactions_user_processed'), 'transactions', ['user_id', 'stripe_processed_at'], unique=False)
    op.create_index(op.f('ix_transactions_stripe_processed_at'), 'transactions', ['stripe_processed_at'], unique=False)
    op.drop_index(op.f('ix_subscription_plans_id'), table_name='subscription_plans')
    op.create_index(op.f('ix_subscription_plans_name'), 'subscription_plans', ['name'], unique=False)
    op.drop_index(op.f('ix_stripe_events_id'), table_name='stripe_events')
    op.drop_index(op.f('ix_processed_files_user_id'), table_name='processed_files')
    op.drop_index(op.f('ix_processed_files_id'), table_name='processed_files')
    # Use conditional drop for file_hash index to handle cases where it was manually removed
    op.execute("DROP INDEX IF EXISTS ix_processed_files_file_hash")
    op.drop_table('processed_files')
    # ### end Alembic commands ###
